version: '3.8'

services:
  java-maven-app:
    image: srvwin/dockerinitial:javamapp-3.0
    ports:
      - "8080:8080"

  Postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"